env: "dev"
app:
  name: "doit-hubspot-sfdc-papi-dev"
  
url:
  recentmodifiedcount: "20"
  
parallelForEach:
  contact-lead:
    maxConcurrency: "5"
  company:
    maxConcurrency: "5"

min-time:
  contact: "1688892668363"
  company: "1688892668363"
  form: "1688371568109"
scheduler:
  frequency: "1"

form:
  Type: "Hubspot Form Fill"
  RecordTypeId : "01276000000CrWY"
  AssignedTo :  "00576000001aTlhAAE" 
  Status : "Completed" 
        
salesforce-sapi:
  host: "doit-salesforce-sapi-dev.us-e2.cloudhub.io"
  port: ""         #for https, Otherwise for http:8081
  protocol: "HTTP"
  basepath: "/api"
  responseBufferSize: "1024"
  maxConnections: "-1"
  connectionIdleTimeout: "30000"
  responseTimeout: "600000"
  baseurl: ""
  reconnection:
    frequency: "2000"
    attempt: "5"
    
hubspot-sapi:
  host: "doit-hubspot-sapi-dev.us-e2.cloudhub.io"
  port: ""         #for https, Otherwise for http:8081    
  protocol: "HTTP"
  basepath: "/api"
  responseBufferSize: "1024"
  maxConnections: "-1"
  connectionIdleTimeout: "30000"
  responseTimeout: "60000"
  baseurl: ""
  reconnection:
    frequency: "2000"
    attempt: "5"