api:
  host: "0.0.0.0"
  port: "8084"
  timeout: "40000"  
      
salesforce:
  token_endpoint: ""
  audience_url: "https://test.salesforce.com"
  system:
    URL: "https://doit-intl--stage.sandbox.my.salesforce.com"
    username: "udit.khare+sandbox1@apisero.com"
    authorization_url: "https://test.salesforce.com/services/Soap/u/55.0"

url:
  recentmodifiedcount: "20"
  
parallelForEach:
  contact-lead:
    maxConcurrency: "5"
  company:
    maxConcurrency: "5"
form:
  Type: "Hubspot Form Fill"
  RecordTypeId : "01276000000CrWY"
  AssignedTo :  "00576000001aTlhAAE" 
  Status : "Completed" 
    
recentcreatedcontact:
  lastmodifiedtime: "1682248414000"
  
salesforce-sapi:
#  host: "doit-salesforce-sapi.us-e2.cloudhub.io"
#  port: ""         #for https, Otherwise for http:8081
  host: "localhost"
  port: "8082"
  protocol: "HTTP"
  basepath: "/api"
  responseBufferSize: "1024"
  maxConnections: "-1"
  connectionIdleTimeout: "30000"
  responseTimeout: "60000"
  baseurl: ""

hubspot-sapi:
#  host: "doit-hubspot-sapi-aj0bf.5sc6y6-3.usa-e2.cloudhub.io"
#  port: ""         #for https, Otherwise for http:8081       
  host: "localhost"
  port: "8081"
  protocol: "HTTP"
  basepath: "/api"
  responseBufferSize: "1024"
  maxConnections: "-1"
  connectionIdleTimeout: "30000"
  responseTimeout: "60000"
  baseurl: ""